services:
  voice-vox:
    image: voicevox/voicevox_engine:cpu-latest
    ports:
      - "50021:50021"

  nuxt:
    container_name: nuxt
    build:
        context: .
        dockerfile: ./docker/nuxt/Dockerfile
    volumes:
      - type: bind
        source: ./front_app
        target: /front_app

    ports:
      - "3000:3000"
      - "24678:24678"
